# Change these first
owner: fhonores # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Novios CL
    url: https://www.noviosfalabella.com/novios-cl/public/inicio.do
  - name: Novios PE
    url: https://www.noviosfalabella.com.pe/novios-pe/public/inicio.do
  - name: Novios CO
    url: https://www.noviosfalabella.com.co/novios-co/public/inicio.do
  - name: Escanea & Paga CL
    url: $EYP_URL
    
asignees:
  - fhonores

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: fhonores.github.io
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DxF Status
  introTitle: "Bienvenidos a **DxF Status**"
  introMessage: Esta página de estado entrega información en tiempo real sobre las **Experiencias**, **Aplicaciones**, **API** y otros servicios de la **Digital eXperience Falabella**
  navbar:
    - title: Status
      href: /upptime
    - title: Abrir un caso 
      href: https://jira.falabella.com/servicedesk/customer/portal/25

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
